# Generated by Django 4.0.6 on 2024-04-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lgo',
            new_name='Logo',
        ),
    ]
