# Generated by Django 4.0.6 on 2024-04-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_lgo_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='capa',
            new_name='imagem',
        ),
    ]
