# Generated by Django 4.0.6 on 2024-04-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='praias/fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('praias', models.ManyToManyField(related_name='servicos', to='praias.praia')),
            ],
        ),
        migrations.CreateModel(
            name='PraiaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='praias.praia')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='praias.servico')),
            ],
        ),
        migrations.AddField(
            model_name='praia',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praias', to='praias.regiao'),
        ),
    ]
