# Generated by Django 4.0.6 on 2024-04-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='praias',
        ),
    ]
