# Generated by Django 4.0.6 on 2024-04-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_album_anolancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='anoLancamento',
            field=models.IntegerField(),
        ),
    ]
