# Generated by Django 4.0.6 on 2024-04-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='hit_da_semana',
            field=models.BooleanField(default=False),
        ),
    ]
