# Generated by Django 4.0.6 on 2024-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_musica_hit_da_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='path',
            field=models.CharField(default="{% url 'bandas:index' %}", max_length=100),
        ),
    ]
