# Generated by Django 4.0.6 on 2024-04-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='path',
            field=models.URLField(default='bandas:index'),
        ),
    ]
