# Generated by Django 4.0.6 on 2024-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0012_musica_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
