# Generated by Django 4.0.6 on 2024-06-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0013_banda_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bandas/fotos'),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(default=''),
        ),
    ]
