# Generated by Django 4.0.6 on 2024-03-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='resposta_pai',
            new_name='resposta',
        ),
    ]
