# Generated by Django 4.0.6 on 2024-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_rename_resposta_pai_resposta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tema',
            field=models.IntegerField(blank=True, choices=[(1, 'Justiça'), (3, 'Saúde'), (4, 'Desporto'), (5, 'Politica'), (6, 'Noticias do Mundo')], default=6, null=True),
        ),
    ]
