# Generated by Django 4.0.6 on 2024-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_alter_artigo_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='tema',
            field=models.IntegerField(blank=True, choices=[(1, 'Justiça'), (3, 'Saúde'), (4, 'Desporto'), (5, 'Política'), (2, 'Cultura'), (6, 'Notícias do Mundo')], default=6, null=True),
        ),
    ]
